umbrella_core:
    webpack:
        dev_server_enable: false
        dev_server_host: http://127.0.0.1
        dev_server_port: 9000
        asset_path: /build/
        asset_pattern_dev: "[name].dev"
        asset_pattern_prod: "[name]_[hash].prod"
    form:
        enable_extension: true
    file:
        asset_path: /uploads/

twig:
    form_themes:
        - 'UmbrellacCoreBundle:Form:layout.html.twig'
        - 'UmbrellacCoreBundle:Form:widget.html.twig'