umbrella_core:
    webpack:
        dev_server_enable: true
        dev_server_port: 9000
        assets_path: /build/

twig:
    form_themes:
        - 'UmbrellaCoreBundle:Form:layout.html.twig'
        - 'UmbrellaCoreBundle:Form:addontext.html.twig'