umbrella_core:
    webpack:
        dev_server_enable: false
        dev_server_host: http://127.0.0.1
        dev_server_port: 9000
        asset_path: /build/
        asset_pattern_dev: "[name].dev"
        asset_pattern_prod: "[name]_[hash].prod"
   form:
       enable_extension: true

twig:
    form_themes:
        - 'UmbrellaCoreBundle:Form:layout.html.twig'
        - 'UmbrellaCoreBundle:Form:widget.html.twig'