services:
    umbrella.form_type_extension:
        class: Umbrella\CoreBundle\Extension\FormTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    umbrella.choice_type_extension:
        class: Umbrella\CoreBundle\Extension\ChoiceTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }