imports:
    - { resource: widgets.yml }
    - { resource: extension.yml }

services:

    # Menu
    umbrella.menu_provider:
        class: Umbrella\CoreBundle\Menu\Provider\MenuProvider
        arguments: ["@service_container", "@umbrella.menu_builder", []]

    umbrella.menu_renderer_provider:
        class: Umbrella\CoreBundle\Menu\Provider\MenuRendererProvider
        arguments: ["@service_container", []]

    umbrella.menu_builder:
        class: Umbrella\CoreBundle\Menu\Builder\MenuBuilder
        arguments: ["@service_container"]

    umbrella.menu_twig:
        class: Umbrella\CoreBundle\Menu\Twig\MenuExtension
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension}

    # Breadcrumb
    umbrella.breadcrumb:
        class: Umbrella\CoreBundle\Breadcrumb\Breadcrumb
        arguments: ["@service_container"]

    umbrella.breadcrumb_twig:
        class: Umbrella\CoreBundle\Breadcrumb\Twig\BreadcrumbExtension
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension}

    # App proxy
    umbrella.app_proxy_service:
        class: Umbrella\CoreBundle\AppProxy\AppProxyService
        arguments: ["@service_container"]

    # DataTable
    umbrella.datatable_factory:
        class: Umbrella\CoreBundle\DataTable\Factory\DataTableFactory
        arguments: ["@service_container"]

    umbrella.datatable_twig:
        class: Umbrella\CoreBundle\DataTable\Twig\DataTableExtension
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension}

    # Toolbar
    umbrella.toolbar_factory:
        class: Umbrella\CoreBundle\Toolbar\Factory\ToolbarFactory
        arguments: ["@service_container"]

    # File
    umbrella.file_manager:
        class: Umbrella\CoreBundle\FileUpload\FileManager
        arguments: ["@service_container"]

    # Subscriber
    umbrella.entity_subscriber:
        class: Umbrella\CoreBundle\Listener\EntitySubscriber
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber }
