services:
    _defaults:
        autowire: true
        public: false

    _instanceof:
        Twig_ExtensionInterface:
            tags:
                - {name: twig.extension}
        Symfony\Component\Form\FormTypeInterface:
            tags:
                - {name: form.type}

    # ---- Component ---- #
    # Menu
    Umbrella\CoreBundle\Component\Menu\MenuProvider:
        arguments: ["@service_container", '@Umbrella\CoreBundle\Component\Menu\MenuBuilder', []]
        public: true

    Umbrella\CoreBundle\Component\Menu\MenuRendererProvider:
        arguments: ["@service_container", []]
        public: true

    Umbrella\CoreBundle\Component\Menu\MenuRouteMatcher:
    Umbrella\CoreBundle\Component\Menu\MenuAuthorizationChecker:
    Umbrella\CoreBundle\Component\Menu\MenuBuilder:
    Umbrella\CoreBundle\Component\Menu\Helper\MenuHelper:
    Umbrella\CoreBundle\Component\Menu\Twig\MenuTwigExtension:

    # Breadcrumb
    Umbrella\CoreBundle\Component\Breadcrumb\Breadcrumb:
        public: true
    Umbrella\CoreBundle\Component\Breadcrumb\Twig\BreadcrumbTwigExtension:

    # App proxy
    Umbrella\CoreBundle\Component\AppProxy\AppMessageBuilder:
        public: true

    # DataTable
    Umbrella\CoreBundle\Component\DataTable\DataTableFactory:
        public: true
    Umbrella\CoreBundle\Component\DataTable\Twig\DataTableTwigExtension:

    # Tree
    Umbrella\CoreBundle\Component\Tree\TreeFactory:
        public: true
    Umbrella\CoreBundle\Component\Tree\Twig\TreeTwigExtension:

    # Toolbar
    Umbrella\CoreBundle\Component\Toolbar\ToolbarFactory:
        public: true
    Umbrella\CoreBundle\Component\Toolbar\Twig\ToolbarTwigExtension:

    # Webpack
    Umbrella\CoreBundle\Component\Webpack\Twig\WebpackTwigExtension:

    # ---- Umbrella ----#

    #Form
    Umbrella\CoreBundle\Form\UmbrellaFileType:
    Umbrella\CoreBundle\Form\Choice2Type:
    Umbrella\CoreBundle\Form\Entity2Type:

    # Services
    Umbrella\CoreBundle\Services\UmbrellaFileUploader:
        public: true
    Umbrella\CoreBundle\Services\SearchHandler:
        public: true

    # Annotation
    Umbrella\CoreBundle\Annotation\SearchableAnnotationReader:

    # Listener
    Umbrella\CoreBundle\Listener\EntitySubscriber:
        tags:
            - {name: doctrine.event_subscriber}
    Umbrella\CoreBundle\Listener\UmbrellaFileListener:
        tags:
            - { name: doctrine.orm.entity_listener }