services:
    _defaults:
        autowire: true

    _instanceof:
        Twig_ExtensionInterface:
            public: false
            tags:
                - {name: twig.extension}

    # ---- Component ---- #
    # Menu
    Umbrella\CoreBundle\Component\Menu\MenuProvider:
        arguments: ["@service_container", '@Umbrella\CoreBundle\Component\Menu\MenuBuilder', []]

    Umbrella\CoreBundle\Component\Menu\MenuRendererProvider:
        arguments: ["@service_container", []]

    Umbrella\CoreBundle\Component\Menu\MenuRouteMatcher:
        public: false
    Umbrella\CoreBundle\Component\Menu\MenuAuthorizationChecker:
        public: false
    Umbrella\CoreBundle\Component\Menu\MenuBuilder:
    Umbrella\CoreBundle\Component\Menu\Twig\MenuTwigExtension:


    # Breadcrumb
    Umbrella\CoreBundle\Component\Breadcrumb\Breadcrumb:
    Umbrella\CoreBundle\Component\Breadcrumb\Twig\BreadcrumbTwigExtension:

    # App proxy
    Umbrella\CoreBundle\Component\AppProxy\AppMessageBuilder:

    # DataTable
    Umbrella\CoreBundle\Component\DataTable\DataTableFactory:
    Umbrella\CoreBundle\Component\DataTable\Twig\DataTableTwigExtension:

    # Tree
    Umbrella\CoreBundle\Component\Tree\TreeFactory:
    Umbrella\CoreBundle\Component\Tree\Twig\TreeTwigExtension:

    # Toolbar
    Umbrella\CoreBundle\Component\Toolbar\ToolbarFactory:

    # Webpack
    Umbrella\CoreBundle\Component\Webpack\Twig\WebpackTwigExtension:


    # ---- Umbrella ----#

    # Searchable
    Umbrella\CoreBundle\Annotation\SearchableAnnotationReader:
    Umbrella\CoreBundle\Handler\SearchHandler:

    # Listener
    Umbrella\CoreBundle\Listener\EntitySubscriber:
        tags:
            - {name: doctrine.event_subscriber}