services:
    _defaults:
        autowire: true

    _instanceof:
        Twig_ExtensionInterface:
            public: false
            tags:
                - {name: twig.extension}
        Symfony\Component\Form\FormTypeInterface:
            public: false
            tags:
                - {name: form.type}

    # ---- Component ---- #
    # Menu
    Umbrella\CoreBundle\Component\Menu\MenuProvider:
        arguments: ["@service_container", '@Umbrella\CoreBundle\Component\Menu\MenuBuilder', []]

    Umbrella\CoreBundle\Component\Menu\MenuRendererProvider:
        arguments: ["@service_container", []]

    Umbrella\CoreBundle\Component\Menu\MenuRouteMatcher:
        public: false
    Umbrella\CoreBundle\Component\Menu\MenuAuthorizationChecker:
        public: false
    Umbrella\CoreBundle\Component\Menu\MenuBuilder:
    Umbrella\CoreBundle\Component\Menu\Helper\MenuHelper:
    Umbrella\CoreBundle\Component\Menu\Twig\MenuTwigExtension:


    # Breadcrumb
    Umbrella\CoreBundle\Component\Breadcrumb\Breadcrumb:
    Umbrella\CoreBundle\Component\Breadcrumb\Twig\BreadcrumbTwigExtension:

    # App proxy
    Umbrella\CoreBundle\Component\AppProxy\AppMessageBuilder:

    # DataTable
    Umbrella\CoreBundle\Component\DataTable\DataTableFactory:
    Umbrella\CoreBundle\Component\DataTable\Twig\DataTableTwigExtension:

    # Tree
    Umbrella\CoreBundle\Component\Tree\TreeFactory:
    Umbrella\CoreBundle\Component\Tree\Twig\TreeTwigExtension:

    # Toolbar
    Umbrella\CoreBundle\Component\Toolbar\ToolbarFactory:

    # Webpack
    Umbrella\CoreBundle\Component\Webpack\Twig\WebpackTwigExtension:

    # ---- Umbrella ----#

    #Form
    Umbrella\CoreBundle\Form\FileUploadType:
    Umbrella\CoreBundle\Form\Choice2Type:
    Umbrella\CoreBundle\Form\Entity2Type:

    # Services
    Umbrella\CoreBundle\Services\UmbrellaFileUploader:
    Umbrella\CoreBundle\Services\SearchHandler:

    # Annotation
    Umbrella\CoreBundle\Annotation\SearchableAnnotationReader:
        public: false

    # Listener
    Umbrella\CoreBundle\Listener\EntitySubscriber:
        public: false
        tags:
            - {name: doctrine.event_subscriber}
    Umbrella\CoreBundle\Listener\UmbrellaFileListener:
        public: false
        tags:
            - { name: doctrine.orm.entity_listener }