services:
    _defaults:
        autowire: true

    _instanceof:
        Twig_ExtensionInterface:
            public: false
            tags:
                - {name: twig.extension}

    # Menu
    Umbrella\CoreBundle\Menu\Provider\MenuProvider:
        arguments: ["@service_container", '@Umbrella\CoreBundle\Menu\Builder\MenuBuilder', []]

    Umbrella\CoreBundle\Menu\Provider\MenuRendererProvider:
        arguments: ["@service_container", []]

    Umbrella\CoreBundle\Menu\Builder\MenuBuilder:
    Umbrella\CoreBundle\Menu\Twig\MenuTwigExtension:

    # Breadcrumb
    Umbrella\CoreBundle\Breadcrumb\Breadcrumb:
    Umbrella\CoreBundle\Breadcrumb\Twig\BreadcrumbTwigExtension:

    # App proxy
    Umbrella\CoreBundle\AppProxy\AppMessageBuilder:

    # DataTable
    Umbrella\CoreBundle\DataTable\Factory\DataTableFactory:
    Umbrella\CoreBundle\DataTable\Twig\DataTableTwigExtension:

    # Toolbar
    Umbrella\CoreBundle\Toolbar\Factory\ToolbarFactory:

    # Webpack
    Umbrella\CoreBundle\Webpack\Twig\WebpackTwigExtension:

    # Searchable
    Umbrella\CoreBundle\Annotation\SearchableAnnotationReader:
    Umbrella\CoreBundle\Handler\SearchHandler:

    # Listener
    Umbrella\CoreBundle\Listener\EntitySubscriber:
        tags:
            - {name: doctrine.event_subscriber}