services:
    umbrella.addontext_widget:
        class: Umbrella\CoreBundle\Form\AddonTextType
        tags:
            - {name: form.type}

    umbrella.datepicker_widget:
        class: Umbrella\CoreBundle\Form\DatepickerType
        tags:
            - {name: form.type}

    umbrella.wysiwyg_widget:
        class: Umbrella\CoreBundle\Form\WysiwygType
        tags:
            - {name: form.type}