services:
    umbrella_admin.datepicker_widget:
        class: Umbrella\CoreBundle\Form\DatepickerType
        tags:
            - {name: form.type}

    umbrella_admin.wysiwyg_widget:
        class: Umbrella\CoreBundle\Form\WysiwygType
        tags:
            - {name: form.type}